import { Worker } from "bullmq";
import { connection } from "@ventry/queue";
import { prisma, decryptToken } from "@ventry/db";

// Simulated AI Generator until you fully wire Groq/Gemini in production
const generateContent = async (type: string, ctx: any) => {
  return "This is a simulated AI reply generated by the background worker.";
};

export const startExecuteActionWorker = () => {
  console.log("Starting BullMQ Workers... Listening for Reply/Action Jobs.");

  const executeWorker = new Worker("replyQueue", async (job) => {
    const { executionId, accountId, text } = job.data;
    console.log(`[Worker][Action] Processing execution ${executionId}`);

    // 1. Fully load the Execution, tracing all the way down to the recipient UI.
    const execution = await prisma.automationExecution.findUnique({
      where: { id: executionId },
      include: {
        message: { include: { thread: true } },
        trigger: {
          include: {
            automation: {
              include: { actions: true }
            }
          }
        }
      }
    });

    if (!execution || !execution.trigger || !execution.trigger.automation) {
       console.error(`[Worker][Action] Invalid structure for ${executionId}`);
       return;
    }

    // 2. Safely resolve payload and targeting
    const action = execution.trigger.automation.actions[0];
    const payloadOpts = (action?.payload as any) || {};
    const recipientId = execution.message?.thread?.externalThreadId;

    if (!recipientId) {
       console.error(`[Worker][Action] Cannot resolve Recipient ID for ${executionId}`);
       return;
    }

    // 3. Resolve and decrypt the Token Pipeline
    const account = await prisma.account.findUnique({ where: { id: accountId } });
    if (!account || !account.accessToken) {
       console.error(`[Worker][Action] No access token found for ${accountId}`);
       return;
    }

    const decryptedToken = decryptToken(account.accessToken);
    if (!decryptedToken) {
       console.error(`[Worker][Action] Token decryption verification failed.`);
       return;
    }

    // 4. Branch Output Mode (AI vs Static)
    let responseText = "";

    if (payloadOpts.useAI) {
      const historyItems = await prisma.message.findMany({
        where: { accountId, threadId: execution.message?.threadId! },
        orderBy: { createdAt: "desc" },
        take: 20
      });
      // Context logic requires chronological order
      historyItems.reverse(); 

      // Simulated LLM Call (Would pipe to OpenAI/Groq here)
      // e.g., await openai.chat.completions.create({...})
      responseText = await generateContent("reply", { text, historyItems });
    } else {
      responseText = payloadOpts.text || "Hello from Ventry!";
    }

    // 5. Fire off to Meta Graph API
    let endpoint = "";
    let body = {};

    if (execution.trigger.type === "COMMENT") {
       // Typically postId stores the mediaId from Meta hook
       const commentId = execution.message?.externalId; // The webhook natively tracks the comment's external ID in message.externalId
       endpoint = `https://graph.facebook.com/v19.0/${commentId}/replies`;
       body = { message: responseText };
    } else {
       // DM branch
       endpoint = `https://graph.facebook.com/v19.0/${account.externalId}/messages`;
       body = { recipient: { id: recipientId }, message: { text: responseText } };
    }

    try {
      console.log(`[Meta][Request] Egressing to Graph API...`);
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${decryptedToken}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(body)
      });

      const result: any = await response.json();

      if (!response.ok) {
         // Terminal Invalidation Catching
         if (result?.error?.code === 190) {
           await prisma.account.update({
             where: { id: accountId },
             data: { tokenValid: false, lastChecked: new Date() }
           });
           console.error("[Worker][Action] Terminal Token revoking triggered.");
         }
         // Rate limit bounce mechanism (BullMQ will catch explicitly)
         else if (result?.error?.code === 4 || result?.error?.code === 17) {
           throw new Error("RATE_LIMIT");
         }

         throw new Error(`Graph API rejection: ${JSON.stringify(result)}`);
      }

      // 6. Finalize Tracker State
      await prisma.automationExecution.update({
        where: { id: execution.id },
        data: { status: "SUCCESS", completedAt: new Date() }
      });
      console.log(`[Worker][Action] Execution ${execution.id} SUCCESS.`);
      
    } catch (err: any) {
      if (err.message === "RATE_LIMIT") throw err; // allow exponential backoff

      await prisma.automationExecution.update({
        where: { id: execution.id },
        data: { status: "FAILED", completedAt: new Date() }
      });
      console.error(`[Worker][Action] Execution ${execution.id} FAILED:`, err);
    }
    
  }, { connection });

  // Standard logging listeners
  executeWorker.on('completed', async (job) => { /* Success handled natively via DB state */ });
  executeWorker.on('failed', async (job, err) => {
     console.error(`[Worker][Action] Job ${job?.id} hard-failed:`, err.message);
  });
};
